### ISSUE TITLE
Frontend Todo Flow: Display and Interact with Todo items

### ISSUE THREAD

**Issue by neebs12** [neebs12/MERN-Todo-App#16]
## Display and Interact with Todo items (Functionality)
Have a Page which displays all the todos for the given user with functionality involved.

## What I need
> Apply a header section which is functionally helpful to the user
- [x] Add a small icon next to the Title :)
- [x] When the user is not yet logged in (no session), just display the application title bar
- [x] When the user is finally logged in, display the logout button on the top right

> Todo Display/Dashboard (Basic - Aesthetic not priority )
- [x] I want to be able to see the todos that is available to this logged in user
- [x] If the user does not have a todo, then we display a button to create a todo instead
- [x] Each Todo will display:
  - [x] Todo Title
  - [x] Todo Description (shortened, think 25 words?)
  - [x] Update and Delete Buttons (non functional)
- [x] I want to have a modal form which allows me add new todos. 
  - This is a prominent button at the top of the dash. Think google mail

> Todo Functionality
- [x] I want to be able to delete when clicking the delete button
- [x] I want to be able to toggle the completion of a todo when clicking on the checkbox
- [x] I want to be able to update a todo when clicking the update button 
  - Think that this modal will be identical to the new todo form - just with pre-filled fields

> Modal
- [x] Add a clear button on the modal (to reset all states within the modal)
