### ISSUE TITLE
Front End Todo Flow: Better Todos

### ISSUE THREAD

**Issue by neebs12** [neebs12/MERN-Todo-App#18]
## Front End Todo Flow: Better Todos
Given the present todos. Better flow. Apply filters on todos.

## What I need
> Unobtrusive loading and others
- [x] Have loading appear as an insolated icon at the bottom left instead of being a whole page
  - Think `zIndex` pattern identical to `AppBar` mui component
- [x] Have a more prominent add new todo button 
  - more height

> All, Completion, Uncompleted
- [x] When all the lists are being shown, I want the 'to be completed' at the top and 'completed' at the bottom
- [x] I want completed todos to be slightly greyed out (?)
  - Think how we can apply this via `sx` styling
- [x] I want to simply be able to click on the name/descr of the todo to 'complete' it
- [x] Add a counter on the All/Completed/Uncompleted
- [x] When I click the sidebar All/Completed/Uncompleted filters, I want the todos to be filtered accordingly
  - If there are no todos being displayed, feel free to display the Add New Todo button. But dont reset the filter todo toggles.

> Search Field at the AppBar
- [x] I want this search field to appear next to the brand
- [x] I want this to only appear once the user has logged in
- [x] I want this to functionally filter through titles and descriptions

> Categories and Filter - **apply this to another issue**
- [ ] Seed categories to existing todos
  - Take advantage of types for monitoring category values
  - Need to change schema of todos on the backend
  - Will be quite involved :/
- [ ] Have categories appear on each todos in todos component. 
  - Think mui chips!
- [ ] Able to toggle multiple categories for a specific todo
  - Think formcontrol with mui
- [ ] Apply category functionality when being added from forms

## Future
- [ ] Sort todos by creation date
  - This need additional information for schema
